ALTER TABLE stock_purchases
MODIFY COLUMN status ENUM('SOLICITADO', 'PAGADO', 'RECIBIDO', 'CANCELADO', 'REEMBOLSADO') NOT NULL DEFAULT 'SOLICITADO',
ADD COLUMN IF NOT EXISTS cancelled_at DATETIME NULL AFTER received_at,
ADD COLUMN IF NOT EXISTS refunded_at DATETIME NULL AFTER cancelled_at;
