ALTER TABLE stock_purchases
ADD COLUMN IF NOT EXISTS supplier_id INT NULL AFTER user_id,
ADD COLUMN IF NOT EXISTS status ENUM('SOLICITADO', 'PAGADO', 'RECIBIDO') NOT NULL DEFAULT 'SOLICITADO' AFTER total,
ADD COLUMN IF NOT EXISTS paid_at DATETIME NULL AFTER created_at,
ADD COLUMN IF NOT EXISTS received_at DATETIME NULL AFTER paid_at;
